### PR TITLE
Fix auto upadate after saving to LoaclStorage

### PR DESCRIPTION
**Pull request by alsabagh-dev**
put the code from line 137 to line 180 in the script.js to a function let's name it 'getDivContainer'. then you call it in document DOMContentLoaded listener and after the you store the receipt in the form submit listener.

### CODE REVIEW

**Comment by peladno** [comment]
> put the code from line 137 to line 180 in the script.js to a function let's name it 'getDivContainer'. then you call it in document DOMContentLoaded listener and after the you store the receipt in the form submit listener.

Thank you so mucho for the help :), I understand what did you do :)!!! it was very simple but I couldn´t know what to do hehehe. Regards from Chile

**Comment by peladno** [comment]
Thank you :)

**Comment by alsabagh-dev** [comment]
you're welcome 😀

**Comment by peladno** [comment]
> you're welcome 😀

Hi, how are you. I'm trying to make a button to delete a recipe, but the button id not working. The js code to delete id at the end. Can you tale a look?

**Pull request closed without merging**
